language: node_js
node_js:
- "stable"
env:
global:
 - export NODE_ENV=test
services:
  - postgresql
before_script:
- psql -c "create user marcus with password 'marcdomain';" -U postgres
- psql -c 'create database fooddb_test;' -U postgres
- npm install
script:
- npm test
- npm run coverage
after_success: npm run coveralls